### ISSUE TITLE
DbHelper creates wrong SQL statement

### ISSUE THREAD

**Issue by projectkit** [fproject/yii2-common#2]
exception 'PDOException' with message 'SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'WHERE userId=1 AND departmentId=1;UPDATE `user_department_assignment` SET  WHERE' at line 1' in F:\GitRepo\fprj-test-server-yii2\vendor\yiisoft\yii2\db\Command.php:844
Stack trace:
#0 F:\GitRepo\fprj-test-server-yii2\vendor\yiisoft\yii2\db\Command.php(844): PDOStatement->execute()
#1 F:\GitRepo\fprj-test-server-yii2\vendor\fproject\yii2-common\fproject\components\DbHelper.php(318): yii\db\Command->execute()
#2 F:\GitRepo\fprj-test-server-yii2\vendor\fproject\yii2-common\fproject\components\DbHelper.php(167): fproject\components\DbHelper::updateMultiple('user_department...', Array, Array, NULL)
#3 F:\GitRepo\fprj-test-server-yii2\vendor\fproject\yii2-restx\fproject\rest\BatchSaveAction.php(80): fproject\components\DbHelper::batchSave(Array, Array)
#4 [internal function]: fproject\rest\BatchSaveAction->run()
#5 F:\GitRepo\fprj-test-server-yii2\vendor\yiisoft\yii2\base\Action.php(92): call_user_func_array(Array, Array)
#6 F:\GitRepo\fprj-test-server-yii2\vendor\yiisoft\yii2\base\Controller.php(154): yii\base\Action->runWithParams(Array)
#7 F:\GitRepo\fprj-test-server-yii2\vendor\yiisoft\yii2\base\Module.php(454): yii\base\Controller->runAction('batch-save', Array)
#8 F:\GitRepo\fprj-test-server-yii2\vendor\yiisoft\yii2\web\Application.php(100): yii\base\Module->runAction('user-department...', Array)
#9 F:\GitRepo\fprj-test-server-yii2\vendor\yiisoft\yii2\base\Application.php(375): yii\web\Application->handleRequest(Object(yii\web\Request))
#10 F:\GitRepo\fprj-test-server-yii2\web\index.php(12): yii\base\Application->run()
#11 {main}

Next exception 'yii\db\Exception' with message 'SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'WHERE userId=1 AND departmentId=1;UPDATE `user_department_assignment` SET  WHERE' at line 1
The SQL being executed was: UPDATE `user_department_assignment` SET  WHERE userId=1 AND departmentId=1;UPDATE `user_department_assignment` SET  WHERE userId=1 AND departmentId=2' in F:\GitRepo\fprj-test-server-yii2\vendor\yiisoft\yii2\db\Schema.php:631
Stack trace:
#0 F:\GitRepo\fprj-test-server-yii2\vendor\yiisoft\yii2\db\Command.php(854): yii\db\Schema->convertException(Object(PDOException), 'UPDATE `user_de...')
#1 F:\GitRepo\fprj-test-server-yii2\vendor\fproject\yii2-common\fproject\components\DbHelper.php(318): yii\db\Command->execute()
#2 F:\GitRepo\fprj-test-server-yii2\vendor\fproject\yii2-common\fproject\components\DbHelper.php(167): fproject\components\DbHelper::updateMultiple('user_department...', Array, Array, NULL)
#3 F:\GitRepo\fprj-test-server-yii2\vendor\fproject\yii2-restx\fproject\rest\BatchSaveAction.php(80): fproject\components\DbHelper::batchSave(Array, Array)
#4 [internal function]: fproject\rest\BatchSaveAction->run()
#5 F:\GitRepo\fprj-test-server-yii2\vendor\yiisoft\yii2\base\Action.php(92): call_user_func_array(Array, Array)
#6 F:\GitRepo\fprj-test-server-yii2\vendor\yiisoft\yii2\base\Controller.php(154): yii\base\Action->runWithParams(Array)
#7 F:\GitRepo\fprj-test-server-yii2\vendor\yiisoft\yii2\base\Module.php(454): yii\base\Controller->runAction('batch-save', Array)
#8 F:\GitRepo\fprj-test-server-yii2\vendor\yiisoft\yii2\web\Application.php(100): yii\base\Module->runAction('user-department...', Array)
#9 F:\GitRepo\fprj-test-server-yii2\vendor\yiisoft\yii2\base\Application.php(375): yii\web\Application->handleRequest(Object(yii\web\Request))
#10 F:\GitRepo\fprj-test-server-yii2\web\index.php(12): yii\base\Application->run()
#11 {main}
Additional Information:
Array
(
    [0] => 42000
    [1] => 1064
    [2] => You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'WHERE userId=1 AND departmentId=1;UPDATE `user_department_assignment` SET  WHERE' at line 1
)

**Comment by ProjectKit** [comment]
This bug occurs when running the testCase601 of the fprj-core-test in FlexUnit

**Comment by ProjectKit** [comment]
Fixed in:
https://github.com/fproject/yii2-common/commit/10908930229f7b3135971aece320e73d4d5a395c
https://github.com/fproject/yii2-common/commit/251629487ef307e9018d1e66efa57019ea1951e3
https://github.com/fproject/yii2-common/commit/d7613731f81a5f26b68c75d7914b3ab721fd4dec
